import { ContractItem, dropdownItem } from "@/types/types";

export const contractTypes: Array<dropdownItem> = [
  { label: "Service Agreement", value: "SERVICE" },
  { label: "Freight Agreement", value: "FREIGHT" },
  { label: "Rate Agreement", value: "RATE" },
];

export const clients: Array<dropdownItem> = [
  { label: "ABC Pvt Ltd", value: "ABC" },
  { label: "DEF Pvt Ltd", value: "DEF" },
  { label: "GHI Pvt Ltd", value: "GHI" },
];

export const transportModes: Array<dropdownItem> = [
  { label: "Sea", value: "SEA" },
  { label: "Air", value: "AIR" },
  { label: "Road", value: "ROAD" },
  { label: "Rail", value: "RAIL" },
];

export const serviceTypes: Array<dropdownItem> = [
  { label: "Door to Door", value: "D2D" },
  { label: "Airport to Airport", value: "A2A" },
  { label: "Airport to Door", value: "A2D" },
  { label: "Port to Port", value: "P2P" },
  { label: "Port to Door", value: "P2D" },
];

export const origins: Array<dropdownItem> = [
  { label: "Kempegowda International Airport", value: "Kempegowda" },
  { label: "Trivandrum International Airport", value: "Trivandrum" },
  { label: "Cochin International Airport", value: "Cochin" },
  { label: "Chennai International Airport", value: "Chennai" },
  { label: "Tiruchirapalli International Airport", value: "Tiruchirapalli" },
  { label: "Rajiv Gandhi International Airport", value: "Rajiv Gandhi" },
  { label: "Visakhapatnam Airport", value: "Visakhapatnam" },
  { label: "Indira Gandhi International Airport", value: "Indira Gandhi" },
  {
    label: "Sardar Vallabhbhai Patel International Airport",
    value: "Sardar Vallabhbhai Patel",
  },
  {
    label: "Chhatrapati Shivaji International Airport",
    value: "Chhatrapati Shivaji",
  },
];

export const destinations: Array<dropdownItem> = [
  { label: "Kempegowda International Airport", value: "Kempegowda" },
  { label: "Trivandrum International Airport", value: "Trivandrum" },
  { label: "Cochin International Airport", value: "Cochin" },
  { label: "Chennai International Airport", value: "Chennai" },
  { label: "Tiruchirapalli International Airport", value: "Tiruchirapalli" },
  { label: "Rajiv Gandhi International Airport", value: "Rajiv Gandhi" },
  { label: "Visakhapatnam Airport", value: "Visakhapatnam" },
  { label: "Indira Gandhi International Airport", value: "Indira Gandhi" },
  {
    label: "Sardar Vallabhbhai Patel International Airport",
    value: "Sardar Vallabhbhai Patel",
  },
  {
    label: "Chhatrapati Shivaji International Airport",
    value: "Chhatrapati Shivaji",
  },
];

export const currencies: Array<dropdownItem> = [
  { label: "UAE Dirham", value: "AED" },
  { label: "Australian Dollar", value: "AUD" },
  { label: "Euro", value: "EUR" },
  { label: "Indian Rupee", value: "INR" },
  { label: "North Korean Won", value: "KPW" },
  { label: "Won", value: "KRW" },
  { label: "Serbian Dinar", value: "RSD" },
  { label: "US Dollar", value: "USD" },
];

export const initialContracts: ContractItem[] = [
  {
    name: "Contract One",
    type: "SERVICE",
    client: "ABC",
    carrier: "Carrier One",
    transportMode: "SEA",
    serviceType: "A2A",
    origin: "Trivandrum",
    destination: "Sardar Vallabhbhai Patel",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "KRW",
    goodsWeight: "1000 Kgs",
    id: "b18fbf1b-e336-48bc-84fa-80bf98eb7c83",
    status: "DRAFT",
  },
  {
    name: "Contract Two",
    type: "RATE",
    client: "DEF",
    carrier: "Carrier Two",
    transportMode: "ROAD",
    serviceType: "P2P",
    origin: "Rajiv Gandhi",
    destination: "Indira Gandhi",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "INR",
    goodsWeight: "5000 Kgs",
    id: "2e108f9b-7b25-497a-b6c8-7ad070b9c962",
    status: "PROCESSED",
  },
  {
    name: "Contract Three",
    type: "FREIGHT",
    client: "GHI",
    carrier: "Carrier Three",
    transportMode: "AIR",
    serviceType: "P2D",
    origin: "Cochin",
    destination: "Kempegowda",
    paymentTerms: "Payment Terms ",
    price: "1001",
    currency: "RSD",
    goodsWeight: "5000 Kgs",
    id: "3a53ad8e-5c2c-4a26-a6af-9f5edf68642c",
    status: "SUBMITTED",
  },
  {
    name: "Contract Four",
    type: "SERVICE",
    client: "DEF",
    carrier: "dafe",
    transportMode: "SEA",
    serviceType: "A2A",
    origin: "Trivandrum",
    destination: "Cochin",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "KRW",
    goodsWeight: "5000 Kgs",
    id: "0771f9cf-0fb1-44cb-9d05-6ca77962b84e",
    status: "ACCEPTED",
  },
  {
    name: "Contract Five",
    type: "RATE",
    client: "GHI",
    carrier: "test",
    transportMode: "ROAD",
    serviceType: "A2D",
    origin: "Cochin",
    destination: "Rajiv Gandhi",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "KPW",
    goodsWeight: "5000 Kgs",
    id: "63314d96-ecba-4764-9d8f-9ee743adae91",
    status: "NEW",
  },
  {
    name: "Contract Six",
    type: "FREIGHT",
    client: "DEF",
    carrier: "Carrier Siz",
    transportMode: "AIR",
    serviceType: "P2P",
    origin: "Trivandrum",
    destination: "Sardar Vallabhbhai Patel",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "INR",
    goodsWeight: "5000 Kgs",
    id: "3aca7731-b697-4407-83a0-277ce692e161",
    status: "SUBMITTED",
  },
  {
    name: "Contract 7",
    type: "SERVICE",
    client: "GHI",
    carrier: "Carrier 8",
    transportMode: "RAIL",
    serviceType: "A2A",
    origin: "Kempegowda",
    destination: "Tiruchirapalli",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "AUD",
    goodsWeight: "5000 Kgs",
    id: "8844085e-a171-40b1-9f48-5fdd52d59d5a",
    status: "NEW",
  },
  {
    name: "Contract 8",
    type: "SERVICE",
    client: "ABC",
    carrier: "Carrier 8",
    transportMode: "SEA",
    serviceType: "D2D",
    origin: "Kempegowda",
    destination: "Chennai",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "INR",
    goodsWeight: "5000 Kgs",
    id: "464bfa38-dc92-4340-a0ab-30a2c5801f33",
    status: "NEW",
  },
  {
    name: "Contract 9",
    type: "SERVICE",
    client: "ABC",
    carrier: "Carrier 9",
    transportMode: "ROAD",
    serviceType: "A2D",
    origin: "Rajiv Gandhi",
    destination: "Indira Gandhi",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "AUD",
    goodsWeight: "5000 Kgs",
    id: "8ea6a36d-4c32-46d8-85e1-1437fec57883",
    status: "DRAFT",
  },
  {
    name: "Contract 10",
    type: "RATE",
    client: "GHI",
    carrier: "fa eafe",
    transportMode: "ROAD",
    serviceType: "A2A",
    origin: "Tiruchirapalli",
    destination: "Visakhapatnam",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "RSD",
    goodsWeight: "5000 Kgs",
    id: "6de7c203-0223-4dbb-bac2-c761af5bee93",
    status: "PROCESSED",
  },
  {
    name: "Contract 11",
    type: "SERVICE",
    client: "DEF",
    carrier: "Carrier 11",
    transportMode: "ROAD",
    serviceType: "A2A",
    origin: "Visakhapatnam",
    destination: "Sardar Vallabhbhai Patel",
    paymentTerms: "Payment Terms ",
    price: "100",
    currency: "KPW",
    goodsWeight: "5000 Kgs",
    id: "dd9d8f5e-1c13-41bd-a708-6217274a7533",
    status: "NEW",
  },
];
